### ISSUE TITLE
can't fetch trie key 

### ISSUE THREAD

**Issue by vivekebics** [zupzup/react-native-ethereum#2]
I have the following error when i click on the button to get the balance. 

```go.Universe$proxyerror: can't fetch trie key d761a9dfb6d3112446987fe37ef421d8927eb1be9b333c23293bf404f4300a16: no suitable peers available```

**Comment by zupzup** [comment]
It seems, as the error message suggests, that the node is not connected to any peers and hence cannot fetch any state.

This can be due to multiple reasons such as connectivity, testnet availability, waiting times, node availability. But it is 100% in geth and has nothing to do with this code-base in particular :)
